# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abe0e166cb084d77d559c49a7d285ae09b3e816bba3f4ae5dfc4cb0a880348c67acdeb3926dc75684cc0cf848f44e6b4f3c165c002d83629a76f438b38db3cb4

test:
  secret_key_base: d456d290169b79605181e9a469c8ccd3b949b168c39571335284a453fa6f967b0da7d048d947a58abfc5cb011c1c358cb01a7ae44c8cd7d6afac529d1926aee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
